// <auto-generated />
namespace MSPress.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FleshingOutErratumObject_more : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FleshingOutErratumObject_more));
        
        string IMigrationMetadata.Id
        {
            get { return "201703292154226_FleshingOutErratumObject_more"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
